version: "3.8"


services:
  # Configuracao NGINX
  nginx:
    build: 
      dockerfile: ./docker/nginx.dockerfile
      context: .
    image: julioszeferino/nginx_fusion:v1
    container_name: nginx
    ports:
      - "8080:80"
    networks:
      - nwfusion
    depends_on:
      - fusion1
      - fusion2
      - fusion3

  # Configuracao Postgres
  pgfusion:
    build:
      dockerfile: ./docker/pgfusion.dockerfile
      context: .
    image: julioszeferino/pgfusion:v1
    container_name: pgfusion
    ports:
      - "5432"
    networks:
      - nwfusion
    volumes:
      - pgdata:/var/lib/postgresql/data

  # Configuracao Fusion1 (instancia app web 1)
  fusion1:
    build:
      dockerfile: ./docker/fusion.dockerfile
      context: .
    image: julioszeferino/fusion1:v1
    container_name: fusion1
    ports:
      - "8000"
    networks:
      - nwfusion
    depends_on:
      - pgfusion

  # Configuracao Fusion2 (instancia app web 2)
  fusion2:
    build:
      dockerfile: ./docker/fusion.dockerfile
      context: .
    image: julioszeferino/fusion2:v1
    container_name: fusion2
    ports:
      - "8000"
    networks:
      - nwfusion
    depends_on:
      - pgfusion

  # Configuracao Fusion3 (instancia app web 3)
  fusion3:
    build:
      dockerfile: ./docker/fusion.dockerfile
      context: .
    image: julioszeferino/fusion3:v1
    container_name: fusion3
    ports:
      - "8000"
    networks:
      - nwfusion
    depends_on:
      - pgfusion


networks:
  nwfusion:
    driver: bridge

volumes:
  pgdata: